import { Repository } from 'typeorm';
import { profile, formations, competances, portfolio } from './myProfile.entity';
export declare class ProfileService {
    private profileRepository;
    private formationsRepository;
    private competancesRepository;
    private portfolioRepository;
    constructor(profileRepository: Repository<profile>, formationsRepository: Repository<formations>, competancesRepository: Repository<competances>, portfolioRepository: Repository<portfolio>);
    takeAllProfile(): Promise<any[]>;
    supProfile(res: any): Promise<void>;
    mouvProfile(res: any, titreModif: any, modif: any): Promise<void>;
    mouvFormation(res: any, titreModif: any, modif: any): Promise<void>;
    mouvCompetance(res: any, titreModif: any, modif: any): Promise<void>;
    mouvPortfolio(res: any, titreModif: any, modif: any): Promise<void>;
    createStructForAllInfoForOneProfile(source: any, res: any): Promise<{
        formations: any[];
        competances: any[];
        portfolio: any[];
        id: number;
        photo: string;
        nom: string;
        prenom: string;
        dateNaissance: string;
        adresse: string;
        mail: string;
        tel: string;
        linkedin: string;
        github: string;
        codingGame: string;
        statu: string;
        password: string;
        disponibilite: string;
        textDescriptif: string;
        contrat: string;
        solde: string;
        nbConnectionCv: number;
    }>;
    addNewProfile(theProfile: any): Promise<void>;
    CheckPassword(mail: any, password: any): Promise<{
        formations: any[];
        competances: any[];
        portfolio: any[];
        id: number;
        photo: string;
        nom: string;
        prenom: string;
        dateNaissance: string;
        adresse: string;
        mail: string;
        tel: string;
        linkedin: string;
        github: string;
        codingGame: string;
        statu: string;
        password: string;
        disponibilite: string;
        textDescriptif: string;
        contrat: string;
        solde: string;
        nbConnectionCv: number;
    }>;
    addNewConnection(id: any): Promise<void>;
}
